openapi: 3.0.3
info:
  title: Core APIs
  description: |-
    universalmacro
  contact:
    email: chenyunda218@gmail.com
  version: 0.0.5
servers:
  - url: https://uat.api.universalmacro.com/core
  - url: https://api.universalmacro.com/core
tags:
  - name: Admin
  - name: Session
  - name: Node
paths:
  /admins:
    post:
      tags: [Admin]
      description: Create user account
      operationId: CreateAdmin
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAdminRequest'
      responses:
        '201':
          description: 'Admin created'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Admin'
    get:
      tags: [Admin]
      description: List Admins
      operationId: ListAdmin
      parameters:
        - $ref: '#/components/parameters/IndexParam'
        - $ref: '#/components/parameters/LimitParam'
      responses:
        '200':
          description: 'List Admin'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdminList'
  /admins/{id}:
    get:
      tags: [Admin]
      description: Get admin info by id
      parameters:
        - $ref: '#/components/parameters/ID'
      operationId: GetAdmin
      responses:
        '200':
          description: 'Get Self info'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Admin'
    delete:
      tags:
        - Admin
      parameters:
        - $ref: '#/components/parameters/ID'
      operationId: DeleteAdmin
      responses:
        '204':
          description: 'Get Self info'
  /admins/{id}/password:
    put:
      tags: [Admin]
      description: Update admin password
      parameters:
        - $ref: '#/components/parameters/ID'
      operationId: UpdateAdminPassword
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePasswordRequest'
      responses:
        '200':
          description: 'Update password success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Admin'
  /admins/{id}/roles:
    put:
      tags: [Admin]
      description: Update admin role
      parameters:
        - $ref: '#/components/parameters/ID'
      operationId: UpdateAdminRole
      requestBody:
        content:
          application/json:
            schema:
              type: string
      responses:
        '200':
          description: 'Update role success'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Role'
  /admins/self:
    get:
      tags: [Admin]
      description: Get admin self info
      operationId: GetAdminSelf
      responses:
        '200':
          description: 'Get Self info'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Admin'
  /admins/self/password:
    put:
      tags: [Admin]
      description: Update admin self password
      operationId: UpdateAdminSelfPassword
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePasswordRequest'
      responses:
        '204':
          description: 'Update password success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Admin'
  /admins/self/totp:
    get:
      tags:
        - Admin
      operationId: GetTotp
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Totp'
    put:
      tags: [Admin]
      description: Update totp
      operationId: UpdateTotp
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTotpRequest'
      responses:
        '204':
          description: 'Update totp success'
  /sessions:
    post:
      tags: [Session]
      description: Create Login session
      operationId: CreateSession
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSessionRequest'
      responses:
        '201':
          description: 'Session created'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'
  /nodes:
    post:
      tags: [Node]
      description: Create node
      operationId: CreateNode
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateNodeRequest'
      responses:
        '201':
          description: 'Node created'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Node'
    get:
      tags: [Node]
      description: List Nodes
      operationId: ListNode
      parameters:
        - $ref: '#/components/parameters/IndexParam'
        - $ref: '#/components/parameters/LimitParam'
      responses:
        '200':
          description: 'List Node'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NodeList'
  /nodes/{id}:
    get:
      tags: [Node]
      description: Get node info by id
      parameters:
        - $ref: '#/components/parameters/ID'
      operationId: GetNode
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: 'Get Node info'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Node'
    delete:
      tags:
        - Node
      parameters:
        - $ref: '#/components/parameters/ID'
      operationId: DeleteNode
      responses:
        '204':
          description: 'Get Self info'
  /nodes/{id}/config:
    get:
      tags: [Node]
      description: Get node info by id
      parameters:
        - $ref: '#/components/parameters/ID'
      operationId: GetNodeConfig
      security:
        - BearerAuth: []
        - ApiKeyAuth: []
      responses:
        '200':
          description: 'Get Node info'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NodeConfig'
        '204':
          description: 'Not set yet'
    patch:
      tags: [Node]
      description: Get node info by id
      parameters:
        - $ref: '#/components/parameters/ID'
      operationId: UpdateNodeConfig
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NodeConfig'
      responses:
        '200':
          description: 'Get Node info'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NodeConfig'
  /nodes/config/api:
    get:
      tags: [Node]
      description: Get node info by domain
      operationId: GetNodeApiConfigByDomain
      parameters:
        - name: domain
          in: query
          schema:
            type: string
          required: true
      responses:
        '200':
          description: 'Get Node info'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiConfig'
        '204':
          description: 'Not set yet'
  /roles:
    get:
      tags: [Role]
      description: List roles
      parameters:
        - $ref: '#/components/parameters/IndexParam'
        - $ref: '#/components/parameters/LimitParam'
      operationId: ListRoles
      responses:
        '200':
          description: 'List roles'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RoleList'
    post:
      tags: [Role]
      description: Create role
      operationId: CreateRole
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRoleRequest'
      responses:
        '201':
          description: 'Role created'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Role'
  /roles/{id}:
    get:
      tags: [Role]
      description: Get role by id
      operationId: GetRole
      parameters:
        - $ref: '#/components/parameters/ID'
      responses:
        '200':
          description: 'Get role'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Role'
    put:
      tags: [Role]
      description: Update role by id
      operationId: UpdateRole
      parameters:
        - $ref: '#/components/parameters/ID'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateRoleRequest'
      responses:
        '200':
          description: 'Role updated'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Role'
    delete:
      tags: [Role]
      description: Delete role by id
      operationId: DeleteRole
      parameters:
        - $ref: '#/components/parameters/ID'
      responses:
        '204':
          description: 'Role deleted'
  /roles/{id}/permissions:
    get:
      tags: [Role]
      description: Get role permissions by id
      operationId: GetRolePermissions
      parameters:
        - $ref: '#/components/parameters/ID'
      responses:
        '200':
          description: 'Get role permissions'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PermissionDomainArray'
    put:
      tags: [Role]
      description: Update role permissions by id
      operationId: UpdateRolePermissions
      parameters:
        - $ref: '#/components/parameters/ID'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PermissionDomainArray'
      responses:
        '200':
          description: 'Role permissions updated'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PermissionDomainArray'
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: ApiKey
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    CreateNodeRequest:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
    NodeList:
      type: object
      required:
        - items
        - pagination
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Node'
        pagination:
          $ref: '#/components/schemas/Pagination'
    Node:
      type: object
      required:
        - id
        - name
        - createdAt
        - updatedAt
      properties:
        id:
          type: string
        name:
          type: string
        securityKey:
          type: string
        description:
          type: string
        createdAt:
          type: integer
          format: int64
        updatedAt:
          type: integer
          format: int64
    NodeConfig:
      type: object
      properties:
        frontendDomain:
          type: string
        api:
          $ref: '#/components/schemas/ApiConfig'
        server:
          $ref: '#/components/schemas/ServerConfig'
        database:
          $ref: '#/components/schemas/DBConfig'
        redis:
          $ref: '#/components/schemas/RedisConfig'
        tencentCloud:
          $ref: '#/components/schemas/TencentCloudConfig'
    RedisConfig:
      type: object
      properties:
        host:
          type: string
        port:
          type: string
        password:
          type: string
    ApiConfig:
      type: object
      properties:
        merchantUrl:
          type: string
    ServerConfig:
      type: object
      properties:
        port:
          type: string
        jwtSecret:
          type: string
    TencentCloudConfig:
      type: object
      properties:
        secretId:
          type: string
        secretKey:
          type: string
        
    DBConfig:
      type: object
      required:
        - host
        - port
        - username
        - password
        - database
      properties:
        host:
          type: string
        port:
          type: string
        username:
          type: string
        password:
          type: string
        database:
          type: string
        type:
          $ref: '#/components/schemas/DatabaseType'
    DatabaseType:
      type: string
      enum: [MYSQL, POSTGRES]
    PhoneNumber:
      type: object
      required:
        - countryCode
        - number
      properties:
        countryCode:
          type: string
        number:
          type: string
    Admin:
      type: object
      required:
        - id
        - account
        - createdAt
        - updatedAt
        - hasTotp
      properties:
        id:
          type: string
        account:
          type: string
        phoneNumber:
          $ref: '#/components/schemas/PhoneNumber'
        role:
          type: string
        hasTotp:
          type: boolean
        createdAt:
          type: integer
          format: int64
        updatedAt:
          type: integer
          format: int64
    AdminList:
      description: 'Account list'
      type: object
      required:
        - items
        - pagination
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Admin'
        pagination:
          $ref: '#/components/schemas/Pagination'
    CreateSessionRequest:
      description: 'Login request'
      type: object
      properties:
        account:
          type: string
        password:
          type: string
    CreateAdminRequest:
      description: 'Create admin request schema'
      required:
        - account
        - password
      type: object
      properties:
        account:
          type: string
        password:
          type: string
        role:
          type: string
    UpdateTotpRequest:
      type: object
      required:
        - url
        - totpCode
      properties:
        url:
          type: string
        totpCode:
          type: string
    Totp:
      type: object
      required:
        - url
      properties:
        url:
          type: string
    CreateRoleRequest:
      description: 'Create role request schema'
      required:
        - name
        - description
      type: object
      properties:
        name:
          type: string
        description:
          type: string
    UpdateRoleRequest:
      description: 'Update role request schema'
      required:
        - name
        - description
      type: object
      properties:
        name:
          type: string
        description:
          type: string
    AddRolesRequest:
      description: 'Add role request schema'
      required:
        - roles
      type: object
      properties:
        rolesIds:
          type: array
          items:
            type: string
    Role:
      type: object
      required:
        - id
        - name
        - description
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
    RoleList:
      type: object
      required:
        - items
        - pagination
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Role'
        pagination:
          $ref: '#/components/schemas/Pagination'
    PermissionDomain:
      type: object
      required:
        - domain
        - description
      properties:
        domain:
          type: string
        description:
          type: string
        permissions:
          type: array
          items:
            type: string
    PermissionDomainArray:
      type: array
      items:
        $ref: '#/components/schemas/PermissionDomain'
    UpdatePasswordRequest:
      type: object
      required:
        - password
      properties:
        password:
          type: string
        oldPassword:
          type: string
    Session:
      type: object
      required:
        - token
      properties:
        token:
          type: string
    Ordering:
      description: 'Ordering'
      type: string
      enum: [ASCENDING, DESCENDING]
    Pagination:
      description: 'Pagination'
      type: object
      required:
        - index
        - limit
        - total
      properties:
        index:
          type: integer
          format: int64
          description: 'Current page'
        limit:
          type: integer
          format: int64
          description: 'Amount per page'
        total:
          type: integer
          format: int64
          description: 'Total page'
  parameters:
    Ordering:
      name: ordering
      description: 'ASCENDING or DESCENDING'
      in: query
      schema:
        $ref: '#/components/schemas/Ordering'
    IndexParam:
      name: index
      in: query
      description: 'Current page index'
      schema:
        type: integer
        format: int64
        minimum: 0
        default: 0
    LimitParam:
      name: limit
      in: query
      description: 'Total pages'
      schema:
        type: integer
        format: int64
        minimum: 1
        default: 1
    ID:
      in: path
      name: id
      schema:
        type: string
      required: true
    StartAt:
      in: query
      name: startAt
      schema:
        type: integer
        format: int64
    EndAt:
      in: query
      name: endAt
      schema:
        type: integer
        format: int64