name: Publish Go Interfaces

on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  REPOSITORY_OWNER: ${{ github.repository_owner }}}
  REPOSITORY_NAME: core-api-interfaces
  EMAIL: "chenyunda218@gmail.com"
  VERSION: "ba0b5a1"
jobs:
  generate-go-client:
    runs-on: ubuntu-latest
    name: Publish Go Interfaces
    steps:
      # Checkout your code
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v4
        with:
          go-version: "^1.21.1"
      - name: Push to core-go-sdk
        run: |
          mkdir go-api-interfaces
          cd go-api-interfaces
          go mod init github.com/universalmacro/core-api-interfaces
          go get github.com/gin-gonic/gin
          go install github.com/universalmacro/openapi-go-generator@${{env.VERSION}}
          go run github.com/universalmacro/openapi-go-generator@${{env.VERSION}} ../openapi.yml core-api-interfaces ./api.go
          cat ./api.go
          git config --global user.email "${{env.EMAIL}}"
          git config --global user.name "Dan Chen"
          go env -w GOPRIVATE=github.com/universalmacro/*
          cp ../git_push.sh .
          sh git_push.sh ${{env.REPOSITORY_OWNER}} ${{env.REPOSITORY_NAME}} ${{ secrets.GIT_TOKEN }}
