name: Publish TS SDK

on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  REPOSITORY_OWNER: ${{ github.repository_owner }}}
  SDK_NAME: "@universalmacro/core-ts-sdk"
jobs:
  generate-typescript-client:
    runs-on: ubuntu-latest
    name: Publish TS SDK
    steps:
      # Checkout your code
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Typescript Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          openapi-file: openapi.yml
          generator: typescript-fetch
          config-file: openapi-ts-config.yml
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
          scope: "@dparty"
      - name: Publish
        run: |
          cd typescript-fetch-client
          npm version `npm view @universalmacro/core-ts-sdk` --no-git-tag-version
          npm version --preid=alpha prerelease --no-git-tag-version
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
