name: Publish Go SDK

on:
  workflow_dispatch:

jobs:
  generate-go-client:
    runs-on: ubuntu-latest
    name: Publish Go SDK
    steps:
      # Checkout your code
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Go Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          openapi-file: openapi.yml
          generator: go
          config-file: openapi-go-config.yml
      - name: Push to core-go-sdk
        run: |
          go env -w GOPRIVATE=github.com/universalmacro/*
          git config --global url."https://${GIT_NAME}:${GIT_TOKEN}@github.com".insteadOf "https://github.com"
          sh git_push.sh universalmacro core-go-sdk
