name: Publish Typescript SDK

on:
  workflow_dispatch:

jobs:
  generate-go-client:
    runs-on: ubuntu-latest
    name: Publish SDK
    steps:
      # Checkout your code
      - name: Checkout
        uses: actions/checkout@v2
      - name: Clone core-go-sdk
        run: |
          git clone git@github.com:universalmacro/core-go-sdk.git
      - name: Generate Go Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          openapi-file: openapi.yml
          generator: go
          config-file: openapi-go-config.yml
